version: '3'

services:  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - 27017:27017
  seller:
    build: ./seller-microservice
    container_name: seller
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb
  buyer:
    build: ./buyer-microservice
    container_name: buyer
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb